# Generated by Django 4.2.7 on 2023-11-26 06:13

import DistribuidoraCarne.validaciones
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DistribuidoraCarne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cai',
            name='fecha_emision',
            field=models.DateField(validators=[DistribuidoraCarne.validaciones.validar_fecha_emision]),
        ),
        migrations.AlterField(
            model_name='cai',
            name='rango_final_factura',
            field=models.IntegerField(validators=[DistribuidoraCarne.validaciones.validar_rango_final]),
        ),
        migrations.AlterField(
            model_name='cai',
            name='rango_inicial_factura',
            field=models.IntegerField(validators=[DistribuidoraCarne.validaciones.validar_rango_inicial]),
        ),
        migrations.AlterField(
            model_name='cai',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.sucursal', validators=[DistribuidoraCarne.validaciones.validar_nombre]),
        ),
        migrations.AlterField(
            model_name='comprasdet',
            name='cantidad',
            field=models.BigIntegerField(default=0, validators=[DistribuidoraCarne.validaciones.validar_cantidad]),
        ),
        migrations.AlterField(
            model_name='comprasdet',
            name='costo',
            field=models.FloatField(default=0, validators=[DistribuidoraCarne.validaciones.validar_costo]),
        ),
        migrations.AlterField(
            model_name='comprasdet',
            name='descuento',
            field=models.FloatField(default=0, validators=[DistribuidoraCarne.validaciones.validar_descuento]),
        ),
        migrations.AlterField(
            model_name='comprasdet',
            name='precio_prv',
            field=models.FloatField(default=0, validators=[DistribuidoraCarne.validaciones.validar_precio_prv]),
        ),
        migrations.AlterField(
            model_name='comprasdet',
            name='sub_total',
            field=models.FloatField(default=0, validators=[DistribuidoraCarne.validaciones.validar_subtotal]),
        ),
        migrations.AlterField(
            model_name='comprasdet',
            name='total',
            field=models.FloatField(default=0, validators=[DistribuidoraCarne.validaciones.validar_total]),
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='descuento',
            field=models.FloatField(default=0, validators=[DistribuidoraCarne.validaciones.validar_descuento]),
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True, validators=[DistribuidoraCarne.validaciones.validar_date_time]),
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='no_factura',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='observacion',
            field=models.TextField(blank=True, null=True, validators=[DistribuidoraCarne.validaciones.validar_descripcion]),
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='sub_total',
            field=models.FloatField(default=0, validators=[DistribuidoraCarne.validaciones.validar_subtotal]),
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='total',
            field=models.FloatField(default=0, validators=[DistribuidoraCarne.validaciones.validar_Total_Cotizacion]),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='costo_entrega',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[DistribuidoraCarne.validaciones.validar_Total_Cotizacion]),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[DistribuidoraCarne.validaciones.validar_direccion]),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='estado_entrega',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[DistribuidoraCarne.validaciones.validar_estado_entrega]),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, validators=[DistribuidoraCarne.validaciones.validar_fecha_entrega]),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='hora_entrega',
            field=models.TimeField(blank=True, null=True, validators=[DistribuidoraCarne.validaciones.validar_hora_entrega]),
        ),
        migrations.AlterField(
            model_name='facturadet',
            name='cantidad',
            field=models.BigIntegerField(default=0, validators=[DistribuidoraCarne.validaciones.validar_cantidad]),
        ),
        migrations.AlterField(
            model_name='facturadet',
            name='descuento',
            field=models.FloatField(default=0, validators=[DistribuidoraCarne.validaciones.validar_descuento]),
        ),
        migrations.AlterField(
            model_name='facturadet',
            name='precio',
            field=models.FloatField(default=0, validators=[DistribuidoraCarne.validaciones.validar_precio]),
        ),
        migrations.AlterField(
            model_name='facturadet',
            name='sub_total',
            field=models.FloatField(default=0, validators=[DistribuidoraCarne.validaciones.validar_subtotal]),
        ),
        migrations.AlterField(
            model_name='facturadet',
            name='total',
            field=models.FloatField(default=0, validators=[DistribuidoraCarne.validaciones.validar_total]),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='descuento',
            field=models.FloatField(default=0, validators=[DistribuidoraCarne.validaciones.validar_descuento]),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, validators=[DistribuidoraCarne.validaciones.validar_fecha_emision]),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='sub_total',
            field=models.FloatField(default=0, validators=[DistribuidoraCarne.validaciones.validar_subtotal]),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='total',
            field=models.FloatField(default=0, validators=[DistribuidoraCarne.validaciones.validar_total]),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='tipo_metodo_pago',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total_pedido',
            field=models.FloatField(validators=[DistribuidoraCarne.validaciones.validar_total_pedido]),
        ),
        migrations.AlterField(
            model_name='preciohistorico',
            name='descripcion_cambio',
            field=models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_descripcion]),
        ),
        migrations.AlterField(
            model_name='preciohistorico',
            name='fecha_inicio',
            field=models.DateField(validators=[DistribuidoraCarne.validaciones.validar_fechas]),
        ),
    ]
